# Generated by Django 2.1.5 on 2019-04-03 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='commentauthor',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commentid',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='comment',
            name='published',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
