# Generated by Django 2.1.7 on 2019-03-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.URLField(null=True),
        ),
    ]
