# Generated by Django 2.1.7 on 2019-03-11 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
