# Generated by Django 2.1.7 on 2019-03-12 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0004_remove_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
