# Generated by Django 2.1.5 on 2019-03-06 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_auto_20190306_2031'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Connection',
            new_name='Friendship',
        ),
    ]
