# Generated by Django 2.1.5 on 2019-03-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_auto_20190306_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='displayName',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='author',
            name='github',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='author',
            name='host',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
