# Generated by Django 2.1.7 on 2019-03-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_auto_20190306_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
