# Generated by Django 2.1.5 on 2019-03-08 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_auto_20190306_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(default='127.0.1.1'),
        ),
    ]
