# Generated by Django 2.1.5 on 2019-03-08 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_auto_20190308_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(default='', max_length=100),
        ),
    ]
