# Generated by Django 2.1.5 on 2019-03-08 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0011_auto_20190308_0340'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('init_id', 'recv_id')},
        ),
    ]
