# Generated by Django 2.1.5 on 2019-03-09 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0012_auto_20190308_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='init_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
