# Generated by Django 2.1.5 on 2019-03-13 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0013_auto_20190308_1814'),
        ('Accounts', '0009_friendship_status'),
    ]

    operations = [
    ]
