# Generated by Django 2.1.5 on 2019-03-13 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0014_merge_20190313_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='recv_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL),
        ),
    ]
