# Generated by Django 2.1.7 on 2019-03-23 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendship',
            old_name='status',
            new_name='state',
        ),
    ]
