# Generated by Django 2.1.7 on 2019-03-26 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20190323_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('foreignHost', models.URLField(default='', primary_key=True, serialize=False)),
                ('sharePosts', models.BooleanField(default=True)),
                ('shareImgs', models.BooleanField(default=True)),
                ('remoteUsername', models.CharField(max_length=50)),
                ('remotePassword', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.CharField(default='None', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node', to=settings.AUTH_USER_MODEL),
        ),
    ]
