# Generated by Django 2.1.7 on 2019-03-26 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_auto_20190325_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='authUser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='node', to=settings.AUTH_USER_MODEL),
        ),
    ]
