# Generated by Django 2.1.7 on 2019-03-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_auto_20190325_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.CharField(blank=True, default='None', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='github',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
